// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/akarasz/yahtzee/events (interfaces: Emitter)

// Package mocks is a generated GoMock package.
package mocks

import (
	events "github.com/akarasz/yahtzee/events"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockEmitter is a mock of Emitter interface
type MockEmitter struct {
	ctrl     *gomock.Controller
	recorder *MockEmitterMockRecorder
}

// MockEmitterMockRecorder is the mock recorder for MockEmitter
type MockEmitterMockRecorder struct {
	mock *MockEmitter
}

// NewMockEmitter creates a new mock instance
func NewMockEmitter(ctrl *gomock.Controller) *MockEmitter {
	mock := &MockEmitter{ctrl: ctrl}
	mock.recorder = &MockEmitterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEmitter) EXPECT() *MockEmitterMockRecorder {
	return m.recorder
}

// Emit mocks base method
func (m *MockEmitter) Emit(arg0 string, arg1 events.Type, arg2 interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Emit", arg0, arg1, arg2)
}

// Emit indicates an expected call of Emit
func (mr *MockEmitterMockRecorder) Emit(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockEmitter)(nil).Emit), arg0, arg1, arg2)
}
