@startuml
Handler -> Controller: //action//
Controller -> Store: load
Store -> Controller
Controller -> ServiceProvider
create Service
ServiceProvider -> Service: create
note right
  model objects are
  immutable - Service
  always returns a new
  object
end note
Controller -> Service: //action//
Service -> Controller:
Controller -> Store: save
Store -> Controller
Controller -> Handler
@enduml
